version: '1'

subgraphs:
  - name: 'employees'
    schema_path: 'subgraphs/employees/schema.graphql'

  - name: 'family'
    schema_path: 'subgraphs/family/schema.graphql'

  - name: 'products'
    schema_path: 'subgraphs/products/schema.graphql'

  - name: 'hobbies'
    schema_path: 'subgraphs/hobbies/schema.graphql'

previews:
  - name: 'my-feature-flag-1'
    namespace: 'default'
    labels:
      - 'team=A'
      - 'team=B'
    subgraphs:
      - name: 'employees'
        routing_url: 'https://employees-api.fly.dev/graphql'
      - name: 'family'
        routing_url: 'https://family-api.fly.dev/graphql'
      - name: 'products'
        routing_url: 'https://product-api-fs.fly.dev/graphql'
      - name: 'hobbies'
        routing_url: 'https://hobbies-api.fly.dev/graphql'

check:
  namespaces:
    - default
