name: 'Cosmo Previews'
description: 'Preview subgraph changes for each pull request using feature flags, a set of subgraph replacements called feature subgraphs.'
author: 'WunderGraph Cosmo'

branding:
  icon: 'git-pull-request'
  color: 'white'

inputs:
  config_path:
    description: 'The path to cosmo.yaml file'
    default: '.github/cosmo.yaml'
  action:
    description: 'The action to perform: preview | schema'
    required: true
  stage:
    description: 'The stage to run. preview: create | update | delete. schema: check'
    required: true
  cosmo_api_key:
    description: 'The API key to authenticate with Cosmo'
    required: true
  github_token:
    description: 'The GitHub token to authenticate with GitHub'
    required: true

outputs:
  feature_subgraphs_to_deploy:
    description: 'The list of feature subgraphs to deploy'

  feature_subgraphs_to_destroy:
    description: 'The list of feature subgraphs to destroy'

runs:
  using: node24
  main: dist/index.mjs
