name: 'Cosmo Previews'
description: 'Preview subgraph changes for each pull request using feature flags, a set of subgraph replacements called feature subgraphs.'
author: 'WunderGraph Cosmo'

branding:
  icon: 'git-pull-request'
  color: 'white'

# Define your inputs here.
inputs:
  config_path:
    description: 'The path to cosmo.yaml file'
    default: '.github/cosmo.yaml'
  create:
    description: 'Create the feature flag + subgraphs from cosmo.yaml'
    default: false
  update:
    description: 'Only update the feature subgraphs from cosmo.yaml'
    default: false
  destroy:
    description: 'Only destroy the feature flag + subgraphs from cosmo.yaml'
    default: false
  cosmo_api_key:
    description: 'The API key to authenticate with Cosmo'
  github_token:
    description: 'The GitHub token to authenticate with GitHub'

outputs:
  feature_subgraphs_to_deploy:
    description: 'The list of feature subgraphs to deploy'

  feature_subgraphs_to_destroy:
    description: 'The list of feature subgraphs to destroy'

runs:
  using: node20
  main: dist/index.js
