name: 'Cosmo Previews'
description: 'Automate PR previews with Graph Feature Flags for seamless testing in a production-like environment.'
author: 'WunderGraph Cosmo'

branding:
  icon: 'eye'
  color: 'white'

# Define your inputs here.
inputs:
  config_path:
    description: 'The path to cosmo.yaml file'
    default: '.github/cosmo.yaml'
  create:
    description: 'Create the feature flag + subgraphs from cosmo.yaml'
    default: false
  update:
    description: 'Only update the feature subgraphs from cosmo.yaml'
    default: false
  destroy:
    description: 'Only destroy the feature flag + subgraphs from cosmo.yaml'
    default: false
  cosmo_api_key:
    description: 'The API key to authenticate with Cosmo'
  github_token:
    description: 'The GitHub token to authenticate with GitHub'

runs:
  using: node20
  main: dist/index.js
